version: '1'

services:
  redis:
    image: "redis:alpine"

    container_name: my_redis

    ports:
      - "6379:6379"

    volumes:
      - redis-data:/data  
    
  my-nest-app:
    depends_on:
      - redis
    
    build:
      dockerfile: Dockerfile
      context: .
    
    image: my-nest-app  

    container_name: my_app 

    ports:
      - "3005:3005"

    environment:
      REDIS_HOST: my_redis
      REDIS_PORT: 6379   

volumes:
  redis-data:

